export const H = { fontFamily: "Barlow Condensed, sans-serif" };
export const AI_KEY = import.meta.env.VITE_ANTHROPIC_API_KEY || "";

export const DEFAULTS = {
  calorieGoal: 2500, proteinGoal: 160, carbsGoal: 280, fatGoal: 75,
  fiberGoal: 30, restTime: 90, units: "kg", measureUnit: "cm", waterGoal: 2500,
  height: "", gender: "male",
};

export const MEALS = ["Breakfast", "Lunch", "Dinner", "Snacks"];
export const DAYS = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
export const CATS = ["Chest", "Back", "Legs", "Shoulders", "Arms", "Core", "Full Body", "Cardio"];

export const MEASURE_FIELDS = [
  { key: "neck", label: "Neck" }, { key: "shoulders", label: "Shoulders" },
  { key: "chest", label: "Chest" }, { key: "bicep_l", label: "Left Bicep" },
  { key: "bicep_r", label: "Right Bicep" }, { key: "waist", label: "Waist" },
  { key: "belly", label: "Belly" }, { key: "hips", label: "Hips" },
  { key: "thigh_l", label: "Left Thigh" }, { key: "thigh_r", label: "Right Thigh" },
  { key: "calf_l", label: "Left Calf" }, { key: "calf_r", label: "Right Calf" },
];

export const BODY_POINTS = [
  { key: "neck", cx: 100, cy: 65 }, { key: "shoulders", cx: 100, cy: 92 },
  { key: "chest", cx: 100, cy: 116 }, { key: "bicep_l", cx: 60, cy: 122 },
  { key: "bicep_r", cx: 140, cy: 122 }, { key: "waist", cx: 100, cy: 148 },
  { key: "belly", cx: 100, cy: 163 }, { key: "hips", cx: 100, cy: 178 },
  { key: "thigh_l", cx: 83, cy: 217 }, { key: "thigh_r", cx: 117, cy: 217 },
  { key: "calf_l", cx: 81, cy: 262 }, { key: "calf_r", cx: 119, cy: 262 },
];

// Muscle groups where increase = progress (green), decrease = bad (red)
export const INCREASE_GOOD = [
  "bicep_l", "bicep_r", "shoulders", "chest", "thigh_l", "thigh_r", "calf_l", "calf_r",
];

export const EX_DB = [
  // ── CHEST ──────────────────────────────────────────────────────────────────
  { id: "bench", name: "Bench Press", cat: "Chest" },
  { id: "incline_bench", name: "Incline Bench Press", cat: "Chest" },
  { id: "decline_bench", name: "Decline Bench Press", cat: "Chest" },
  { id: "db_bench", name: "Dumbbell Bench Press", cat: "Chest" },
  { id: "incline_db_bench", name: "Incline Dumbbell Press", cat: "Chest" },
  { id: "decline_db_bench", name: "Decline Dumbbell Press", cat: "Chest" },
  { id: "cable_fly", name: "Cable Fly", cat: "Chest" },
  { id: "incline_cable_fly", name: "Incline Cable Fly", cat: "Chest" },
  { id: "db_fly", name: "Dumbbell Fly", cat: "Chest" },
  { id: "incline_db_fly", name: "Incline Dumbbell Fly", cat: "Chest" },
  { id: "pushup", name: "Push Up", cat: "Chest" },
  { id: "wide_pushup", name: "Wide Push Up", cat: "Chest" },
  { id: "diamond_pushup", name: "Diamond Push Up", cat: "Chest" },
  { id: "decline_pushup", name: "Decline Push Up", cat: "Chest" },
  { id: "chest_dip", name: "Chest Dip", cat: "Chest" },
  { id: "pec_deck", name: "Pec Deck Machine", cat: "Chest" },
  { id: "chest_press_machine", name: "Chest Press Machine", cat: "Chest" },
  { id: "landmine_press", name: "Landmine Press", cat: "Chest" },
  { id: "svend_press", name: "Svend Press", cat: "Chest" },

  // ── BACK ───────────────────────────────────────────────────────────────────
  { id: "deadlift", name: "Deadlift", cat: "Back" },
  { id: "sumo_deadlift", name: "Sumo Deadlift", cat: "Back" },
  { id: "trap_bar_deadlift", name: "Trap Bar Deadlift", cat: "Back" },
  { id: "barbell_row", name: "Barbell Row", cat: "Back" },
  { id: "pendlay_row", name: "Pendlay Row", cat: "Back" },
  { id: "tbar_row", name: "T-Bar Row", cat: "Back" },
  { id: "pullup", name: "Pull Up", cat: "Back" },
  { id: "chinup", name: "Chin Up", cat: "Back" },
  { id: "neutral_pullup", name: "Neutral Grip Pull Up", cat: "Back" },
  { id: "lat_pulldown", name: "Lat Pulldown", cat: "Back" },
  { id: "close_lat_pulldown", name: "Close Grip Lat Pulldown", cat: "Back" },
  { id: "seated_row", name: "Seated Cable Row", cat: "Back" },
  { id: "db_row", name: "Dumbbell Row", cat: "Back" },
  { id: "chest_supported_row", name: "Chest Supported Row", cat: "Back" },
  { id: "face_pull", name: "Face Pull", cat: "Back" },
  { id: "straight_arm_pulldown", name: "Straight Arm Pulldown", cat: "Back" },
  { id: "pullover", name: "Dumbbell Pullover", cat: "Back" },
  { id: "hyperextension", name: "Back Extension", cat: "Back" },
  { id: "good_morning", name: "Good Morning", cat: "Back" },
  { id: "inverted_row", name: "Inverted Row", cat: "Back" },
  { id: "rack_pull", name: "Rack Pull", cat: "Back" },
  { id: "shrug", name: "Barbell Shrug", cat: "Back" },
  { id: "db_shrug", name: "Dumbbell Shrug", cat: "Back" },

  // ── LEGS ───────────────────────────────────────────────────────────────────
  { id: "back_squat", name: "Back Squat", cat: "Legs" },
  { id: "front_squat", name: "Front Squat", cat: "Legs" },
  { id: "goblet_squat", name: "Goblet Squat", cat: "Legs" },
  { id: "sumo_squat", name: "Sumo Squat", cat: "Legs" },
  { id: "bulgarian_split", name: "Bulgarian Split Squat", cat: "Legs" },
  { id: "leg_press", name: "Leg Press", cat: "Legs" },
  { id: "hack_squat", name: "Hack Squat", cat: "Legs" },
  { id: "rdl", name: "Romanian Deadlift", cat: "Legs" },
  { id: "single_leg_rdl", name: "Single Leg RDL", cat: "Legs" },
  { id: "leg_curl", name: "Leg Curl", cat: "Legs" },
  { id: "seated_leg_curl", name: "Seated Leg Curl", cat: "Legs" },
  { id: "leg_extension", name: "Leg Extension", cat: "Legs" },
  { id: "lunge", name: "Lunge", cat: "Legs" },
  { id: "walking_lunge", name: "Walking Lunge", cat: "Legs" },
  { id: "reverse_lunge", name: "Reverse Lunge", cat: "Legs" },
  { id: "step_up", name: "Step Up", cat: "Legs" },
  { id: "calf_raise", name: "Calf Raise", cat: "Legs" },
  { id: "seated_calf", name: "Seated Calf Raise", cat: "Legs" },
  { id: "hip_thrust", name: "Hip Thrust", cat: "Legs" },
  { id: "glute_bridge", name: "Glute Bridge", cat: "Legs" },
  { id: "box_squat", name: "Box Squat", cat: "Legs" },
  { id: "sissy_squat", name: "Sissy Squat", cat: "Legs" },
  { id: "wall_sit", name: "Wall Sit", cat: "Legs" },
  { id: "nordic_curl", name: "Nordic Curl", cat: "Legs" },
  { id: "adductor_machine", name: "Adductor Machine", cat: "Legs" },
  { id: "abductor_machine", name: "Abductor Machine", cat: "Legs" },

  // ── SHOULDERS ──────────────────────────────────────────────────────────────
  { id: "ohp", name: "Overhead Press", cat: "Shoulders" },
  { id: "db_ohp", name: "Dumbbell OHP", cat: "Shoulders" },
  { id: "seated_db_press", name: "Seated Dumbbell Press", cat: "Shoulders" },
  { id: "arnold_press", name: "Arnold Press", cat: "Shoulders" },
  { id: "push_press", name: "Push Press", cat: "Shoulders" },
  { id: "lat_raise", name: "Lateral Raise", cat: "Shoulders" },
  { id: "cable_lat_raise", name: "Cable Lateral Raise", cat: "Shoulders" },
  { id: "front_raise", name: "Front Raise", cat: "Shoulders" },
  { id: "rear_delt_fly", name: "Rear Delt Fly", cat: "Shoulders" },
  { id: "cable_rear_delt", name: "Cable Rear Delt Fly", cat: "Shoulders" },
  { id: "upright_row", name: "Upright Row", cat: "Shoulders" },
  { id: "machine_shoulder_press", name: "Machine Shoulder Press", cat: "Shoulders" },
  { id: "plate_raise", name: "Plate Front Raise", cat: "Shoulders" },
  { id: "band_pull_apart", name: "Band Pull Apart", cat: "Shoulders" },

  // ── ARMS ───────────────────────────────────────────────────────────────────
  { id: "barbell_curl", name: "Barbell Curl", cat: "Arms" },
  { id: "db_curl", name: "Dumbbell Curl", cat: "Arms" },
  { id: "hammer_curl", name: "Hammer Curl", cat: "Arms" },
  { id: "incline_db_curl", name: "Incline Dumbbell Curl", cat: "Arms" },
  { id: "concentration_curl", name: "Concentration Curl", cat: "Arms" },
  { id: "spider_curl", name: "Spider Curl", cat: "Arms" },
  { id: "cable_curl", name: "Cable Curl", cat: "Arms" },
  { id: "preacher_curl", name: "Preacher Curl", cat: "Arms" },
  { id: "reverse_curl", name: "Reverse Curl", cat: "Arms" },
  { id: "zottman_curl", name: "Zottman Curl", cat: "Arms" },
  { id: "tricep_pushdown", name: "Tricep Pushdown", cat: "Arms" },
  { id: "rope_pushdown", name: "Rope Pushdown", cat: "Arms" },
  { id: "skull_crusher", name: "Skull Crusher", cat: "Arms" },
  { id: "overhead_tricep", name: "Overhead Tricep Extension", cat: "Arms" },
  { id: "tricep_dip", name: "Tricep Dip", cat: "Arms" },
  { id: "close_grip_bench", name: "Close Grip Bench Press", cat: "Arms" },
  { id: "tricep_kickback", name: "Tricep Kickback", cat: "Arms" },
  { id: "wrist_curl", name: "Wrist Curl", cat: "Arms" },
  { id: "reverse_wrist_curl", name: "Reverse Wrist Curl", cat: "Arms" },

  // ── CORE ───────────────────────────────────────────────────────────────────
  { id: "plank", name: "Plank", cat: "Core" },
  { id: "side_plank", name: "Side Plank", cat: "Core" },
  { id: "crunch", name: "Crunch", cat: "Core" },
  { id: "situp", name: "Sit Up", cat: "Core" },
  { id: "leg_raise", name: "Leg Raise", cat: "Core" },
  { id: "hanging_leg_raise", name: "Hanging Leg Raise", cat: "Core" },
  { id: "knee_raise", name: "Hanging Knee Raise", cat: "Core" },
  { id: "russian_twist", name: "Russian Twist", cat: "Core" },
  { id: "ab_wheel", name: "Ab Wheel Rollout", cat: "Core" },
  { id: "bicycle_crunch", name: "Bicycle Crunch", cat: "Core" },
  { id: "cable_crunch", name: "Cable Crunch", cat: "Core" },
  { id: "wood_chop", name: "Cable Wood Chop", cat: "Core" },
  { id: "pallof_press", name: "Pallof Press", cat: "Core" },
  { id: "dead_bug", name: "Dead Bug", cat: "Core" },
  { id: "bird_dog", name: "Bird Dog", cat: "Core" },
  { id: "mountain_climber", name: "Mountain Climber", cat: "Core" },
  { id: "toe_touch", name: "Toe Touch Crunch", cat: "Core" },
  { id: "flutter_kick", name: "Flutter Kicks", cat: "Core" },
  { id: "hollow_hold", name: "Hollow Body Hold", cat: "Core" },
  { id: "v_up", name: "V-Up", cat: "Core" },
  { id: "dragon_flag", name: "Dragon Flag", cat: "Core" },

  // ── FULL BODY ──────────────────────────────────────────────────────────────
  { id: "burpee", name: "Burpee", cat: "Full Body" },
  { id: "clean", name: "Power Clean", cat: "Full Body" },
  { id: "clean_jerk", name: "Clean & Jerk", cat: "Full Body" },
  { id: "snatch", name: "Snatch", cat: "Full Body" },
  { id: "thruster", name: "Thruster", cat: "Full Body" },
  { id: "kb_swing", name: "Kettlebell Swing", cat: "Full Body" },
  { id: "kb_clean", name: "Kettlebell Clean", cat: "Full Body" },
  { id: "kb_snatch", name: "Kettlebell Snatch", cat: "Full Body" },
  { id: "kb_goblet", name: "Kettlebell Goblet Squat", cat: "Full Body" },
  { id: "kb_press", name: "Kettlebell Press", cat: "Full Body" },
  { id: "farmers_carry", name: "Farmer's Carry", cat: "Full Body" },
  { id: "suitcase_carry", name: "Suitcase Carry", cat: "Full Body" },
  { id: "turkish_getup", name: "Turkish Get Up", cat: "Full Body" },
  { id: "box_jump", name: "Box Jump", cat: "Full Body" },
  { id: "broad_jump", name: "Broad Jump", cat: "Full Body" },
  { id: "battle_rope", name: "Battle Ropes", cat: "Full Body" },
  { id: "sled_push", name: "Sled Push", cat: "Full Body" },
  { id: "sled_pull", name: "Sled Pull", cat: "Full Body" },

  // ── CARDIO ─────────────────────────────────────────────────────────────────
  { id: "running", name: "Running", cat: "Cardio", cardio: true },
  { id: "jogging", name: "Jogging", cat: "Cardio", cardio: true },
  { id: "walking", name: "Walking", cat: "Cardio", cardio: true },
  { id: "cycling", name: "Cycling", cat: "Cardio", cardio: true },
  { id: "swimming", name: "Swimming", cat: "Cardio", cardio: true },
  { id: "rowing", name: "Rowing Machine", cat: "Cardio", cardio: true },
  { id: "hiit", name: "HIIT", cat: "Cardio", cardio: true },
  { id: "elliptical", name: "Elliptical", cat: "Cardio", cardio: true },
  { id: "stair_climber", name: "Stair Climber", cat: "Cardio", cardio: true },
  { id: "jump_rope", name: "Jump Rope", cat: "Cardio", cardio: true },
  { id: "treadmill", name: "Treadmill", cat: "Cardio", cardio: true },
  { id: "sprint", name: "Sprint Intervals", cat: "Cardio", cardio: true },
  { id: "assault_bike", name: "Assault Bike", cat: "Cardio", cardio: true },
  { id: "ski_erg", name: "Ski Erg", cat: "Cardio", cardio: true },
];
